version: '3.8'

services:
  fastapi_app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow
    deploy:
      resources:
        limits:
          cpus: '1.50'
          memory: 4G
    networks:
      - sentiment-network

  frontend:
    build:
      context: ./app/sentiment-analysis-chatbot
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - fastapi_app
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
    networks:
      - sentiment-network

  prometheus:
    image: prom/prometheus:v2.45.0
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./infra/prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml
    ports:
      - "9091:9090"
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      - sentiment-network

  grafana:
    image: grafana/grafana:10.0.0
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./infra/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      - sentiment-network

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.4.1
    ports:
      - "5005:5000"
    command: mlflow server --host 0.0.0.0 --port 5000
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1G
    networks:
      - sentiment-network

networks:
  sentiment-network:
    driver: bridge
